export { default as MinusSVG } from './minus.svg'
export { default as LevelSVG } from './level.svg'
export { default as ArrowLeftSVG } from './arrow-left.svg'
export { default as ExclamationSVG } from './exclamation.svg'
export { default as TickSVG } from './tick.svg'
export { default as XSVG } from './x.svg'
export { default as TimesSVG } from './times.svg'
export { default as WarningSVG } from './warning.svg'
